In [49]:
import pandas as pd

In [50]:
df_silver = pd.read_csv("dados/bronze/history_bronze.csv")

In [51]:
# verificando nulos e duplicidades

print("TOTAL DE NULOS: ",df_silver.isnull().sum())
print(" ")
print("TOTAL DE DUPLICATAS: ",df_silver.duplicated().sum())

TOTAL DE NULOS:  customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

TOTAL DE DUPLICATAS:  0

## Tradução das colunas

In [52]:
## Tradução para pt-br

df_silver = df_silver.rename(columns={
    "customerID": "ID_Cliente",
    "gender": "Genero",
    "SeniorCitizen": "Cliente_Idoso",
    "Partner": "Parceiro",
    "Dependents": "Dependentes",
    "tenure": "Tempo_Permanencia(MESES)",
    "PhoneService": "Servico_Telefonico",
    "MultipleLines": "Multiplas_Linhas",
    "InternetService": "Servico_Internet",
    "OnlineSecurity": "Seguranca_Online",
    "OnlineBackup": "Backup_Online",
    "DeviceProtection": "Protecao_Dispositivo",
    "TechSupport": "Suporte_Tecnico",
    "StreamingTV": "Streaming_TV",
    "StreamingMovies": "Streaming_Filmes",
    "Contract": "Contrato",
    "PaperlessBilling": "Faturamento_Sem_Papel",
    "PaymentMethod": "Metodo_Pagamento",
    "MonthlyCharges": "Cobranca_Mensal",
    "TotalCharges": "Cobranca_Total",
    "Churn": "Cancelamento",
    "CustomerFeedback": "Feedback_Cliente",
    "MonthlyIncome": "Renda_Mensal"
})

## Verificando se os dados nulos tem correlação com outras variaveis

In [53]:
# verificando a coluna totalcharges para tratamento
pd.set_option('display.max_columns', None)
df_silver.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,Yes,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

In [54]:
df_nulos = df_silver[df_silver["Cobranca_Total"].isnull()]

In [55]:
df_nulos.shape[0]

278

In [56]:

pd.crosstab(
    df_nulos["Cobranca_Total"].isnull(),
    df_nulos["Cancelamento"]
)

Cancelamento     No  Yes
Cobranca_Total
True            186   92

In [57]:
df_nulos.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,Yes,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
49,6996-KNSML,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,74.90,NaN,Yes,I recently switched to this internet provider ...,5422
64,4951-UKAAQ,Female,0,No,No,4,Yes,Yes,Fiber optic,No,Yes,No,No,No,Yes,Month-to-month,Yes,Electronic check,88.95,NaN,Yes,I recently decided to cancel my fiber optic in...,1323
79,9360-AHGNL,Female,1,Yes,No,43,Yes,Yes,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,109.55,NaN,Yes,I have been a customer with this company for o...,6588
122,7253-UVNDW,Female,0,No,No,46,Yes,No,DSL,No,No,Yes,Yes,No,No,Two year,No,Credit card (automatic),54.35,NaN,Yes,I have been a customer with this company for 4...,5277

In [58]:
df_nulos["Tempo_Permanencia(MESES)"].describe()

count     278
unique     70
top         1
freq       26
Name: Tempo_Permanencia(MESES), dtype: object

In [59]:

coluna = "Tempo_Permanencia(MESES)"

# Substituindo "unknown" por 0
df_silver[coluna] = df_silver[coluna].replace("unknown", "0")

# Convertendo para inteiro
df_silver[coluna] = pd.to_numeric(
    df_silver[coluna]
).astype("Int8")

print("Total de nulos:", df_silver[coluna].isnull().sum())
print(df_silver[coluna].dtype)

Total de nulos: 0
Int8

In [60]:
# verificando nulos e duplicidades

print("TOTAL DE NULOS: ",df_silver.isnull().sum())
print(" ")
print("TOTAL DE DUPLICATAS: ",df_silver.duplicated().sum())

TOTAL DE NULOS:  ID_Cliente                    0
Genero                        0
Cliente_Idoso                 0
Parceiro                      0
Dependentes                   0
Tempo_Permanencia(MESES)      0
Servico_Telefonico            0
Multiplas_Linhas              0
Servico_Internet              0
Seguranca_Online              0
Backup_Online                 0
Protecao_Dispositivo          0
Suporte_Tecnico               0
Streaming_TV                  0
Streaming_Filmes              0
Contrato                      0
Faturamento_Sem_Papel         0
Metodo_Pagamento              0
Cobranca_Mensal               0
Cobranca_Total              278
Cancelamento                  0
Feedback_Cliente              0
Renda_Mensal                  0
dtype: int64

TOTAL DE DUPLICATAS:  0

## Mudando a tipagem dos dados e padronizando os formatos

In [61]:
df_silver.dtypes

ID_Cliente                   object
Genero                       object
Cliente_Idoso                 int64
Parceiro                     object
Dependentes                  object
Tempo_Permanencia(MESES)       Int8
Servico_Telefonico           object
Multiplas_Linhas             object
Servico_Internet             object
Seguranca_Online             object
Backup_Online                object
Protecao_Dispositivo         object
Suporte_Tecnico              object
Streaming_TV                 object
Streaming_Filmes             object
Contrato                     object
Faturamento_Sem_Papel        object
Metodo_Pagamento             object
Cobranca_Mensal             float64
Cobranca_Total              float64
Cancelamento                 object
Feedback_Cliente             object
Renda_Mensal                  int64
dtype: object

In [62]:
df_silver = df_silver.astype({
    "ID_Cliente": "string",
    "Genero": "category",
    "Cliente_Idoso": "bool",
    "Parceiro": "category",
    "Dependentes": "category",
    "Tempo_Permanencia(MESES)": "Int8",
    "Servico_Telefonico": "category",
    "Multiplas_Linhas": "category",
    "Servico_Internet": "category",
    "Seguranca_Online": "category",
    "Backup_Online": "category",
    "Protecao_Dispositivo": "category",
    "Suporte_Tecnico": "category",
    "Streaming_TV": "category",
    "Streaming_Filmes": "category",
    "Contrato": "category",
    "Faturamento_Sem_Papel": "category",
    "Metodo_Pagamento": "category",
    "Cobranca_Mensal": "float32",
    "Cobranca_Total": "float32",
    "Cancelamento": "category",
    "Feedback_Cliente": "string",
    "Renda_Mensal": "int32"
})

In [63]:
df_silver.dtypes

ID_Cliente                  string[python]
Genero                            category
Cliente_Idoso                         bool
Parceiro                          category
Dependentes                       category
Tempo_Permanencia(MESES)              Int8
Servico_Telefonico                category
Multiplas_Linhas                  category
Servico_Internet                  category
Seguranca_Online                  category
Backup_Online                     category
Protecao_Dispositivo              category
Suporte_Tecnico                   category
Streaming_TV                      category
Streaming_Filmes                  category
Contrato                          category
Faturamento_Sem_Papel             category
Metodo_Pagamento                  category
Cobranca_Mensal                    float32
Cobranca_Total                     float32
Cancelamento                      category
Feedback_Cliente            string[python]
Renda_Mensal                         int32
dtype: object

In [64]:
# verificando nulos e duplicidades

print("TOTAL DE NULOS: ",df_silver.isnull().sum())
print(" ")
print("TOTAL DE DUPLICATAS: ",df_silver.duplicated().sum())

TOTAL DE NULOS:  ID_Cliente                    0
Genero                        0
Cliente_Idoso                 0
Parceiro                      0
Dependentes                   0
Tempo_Permanencia(MESES)      0
Servico_Telefonico            0
Multiplas_Linhas              0
Servico_Internet              0
Seguranca_Online              0
Backup_Online                 0
Protecao_Dispositivo          0
Suporte_Tecnico               0
Streaming_TV                  0
Streaming_Filmes              0
Contrato                      0
Faturamento_Sem_Papel         0
Metodo_Pagamento              0
Cobranca_Mensal               0
Cobranca_Total              278
Cancelamento                  0
Feedback_Cliente              0
Renda_Mensal                  0
dtype: int64

TOTAL DE DUPLICATAS:  0

In [65]:
df_silver.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
0,4578-PHJYZ,Male,False,Yes,Yes,52,Yes,No,DSL,No,Yes,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.750000,3482.850098,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,False,Yes,Yes,33,Yes,No,DSL,No,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,73.900002,2405.050049,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,True,No,No,22,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,20.049999,417.000000,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,True,Yes,Yes,28,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,35.900002,973.650024,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,False,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.300003,144.000000,No,I have been using the fiber optic internet ser...,1691

In [66]:
# Preenchendo os valores nulos de Cobranca_Total
mascara = df_silver["Cobranca_Total"].isna()

df_silver.loc[mascara, "Cobranca_Total"] = (
    df_silver.loc[mascara, "Tempo_Permanencia(MESES)"]
    * df_silver.loc[mascara, "Cobranca_Mensal"]
)

# Conferindo o resultado
print("Nulos restantes:", df_silver["Cobranca_Total"].isna().sum())
print("Valores preenchidos:", mascara.sum())

Nulos restantes: 0
Valores preenchidos: 278

In [67]:
# verificando nulos e duplicidades

print("TOTAL DE NULOS: ",df_silver.isnull().sum())
print(" ")
print("TOTAL DE DUPLICATAS: ",df_silver.duplicated().sum())

TOTAL DE NULOS:  ID_Cliente                  0
Genero                      0
Cliente_Idoso               0
Parceiro                    0
Dependentes                 0
Tempo_Permanencia(MESES)    0
Servico_Telefonico          0
Multiplas_Linhas            0
Servico_Internet            0
Seguranca_Online            0
Backup_Online               0
Protecao_Dispositivo        0
Suporte_Tecnico             0
Streaming_TV                0
Streaming_Filmes            0
Contrato                    0
Faturamento_Sem_Papel       0
Metodo_Pagamento            0
Cobranca_Mensal             0
Cobranca_Total              0
Cancelamento                0
Feedback_Cliente            0
Renda_Mensal                0
dtype: int64

TOTAL DE DUPLICATAS:  0

In [68]:
df_silver.to_csv(
    "history_silver.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV da camada Silver gerado com sucesso!")

CSV da camada Silver gerado com sucesso!