In [1]:
import pandas as pd

In [2]:
df_silver = pd.read_csv("dados/bronze/history_bronze.csv")

In [7]:
# verificando nulos e duplicidades

print("TOTAL DE NULOS: ",df_silver.isnull().sum())
print(" ")
print("TOTAL DE DUPLICATAS: ",df_silver.duplicated().sum())

TOTAL DE NULOS:  customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

TOTAL DE DUPLICATAS:  0

## Tradução das colunas

In [68]:
## Tradução para pt-br

df_silver = df_silver.rename(columns={
    "customerID": "ID_Cliente",
    "gender": "Genero",
    "SeniorCitizen": "Cliente_Idoso",
    "Partner": "Parceiro",
    "Dependents": "Dependentes",
    "tenure": "Tempo_Permanencia(MESES)",
    "PhoneService": "Servico_Telefonico",
    "MultipleLines": "Multiplas_Linhas",
    "InternetService": "Servico_Internet",
    "OnlineSecurity": "Seguranca_Online",
    "OnlineBackup": "Backup_Online",
    "DeviceProtection": "Protecao_Dispositivo",
    "TechSupport": "Suporte_Tecnico",
    "StreamingTV": "Streaming_TV",
    "StreamingMovies": "Streaming_Filmes",
    "Contract": "Contrato",
    "PaperlessBilling": "Faturamento_Sem_Papel",
    "PaymentMethod": "Metodo_Pagamento",
    "MonthlyCharges": "Cobranca_Mensal",
    "TotalCharges": "Cobranca_Total",
    "Churn": "Cancelamento",
    "CustomerFeedback": "Feedback_Cliente",
    "MonthlyIncome": "Renda_Mensal"
})

## Verificando se os dados nulos tem correlação com outras variaveis

In [69]:
# verificando a coluna totalcharges para tratamento
pd.set_option('display.max_columns', None)
df_silver.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
0,4578-PHJYZ,Male,False,Yes,Yes,52,Yes,No,DSL,No,Yes,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.750000,3482.850098,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,False,Yes,Yes,33,Yes,No,DSL,No,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,73.900002,2405.050049,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,True,No,No,22,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,20.049999,417.000000,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,True,Yes,Yes,28,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,35.900002,973.650024,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,False,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.300003,144.000000,No,I have been using the fiber optic internet ser...,1691

In [60]:
df_nulos = df_silver[df_silver["Cobranca_Total"].isnull()]

In [53]:
df_nulos.shape[0]

278

In [54]:

pd.crosstab(
    df_nulos["Cobranca_Total"].isnull(),
    df_nulos["Cancelamento"]
)

Cancelamento     No  Yes
Cobranca_Total
True            186   92

In [56]:
df_nulos.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,Yes,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
49,6996-KNSML,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,74.90,NaN,Yes,I recently switched to this internet provider ...,5422
64,4951-UKAAQ,Female,0,No,No,4,Yes,Yes,Fiber optic,No,Yes,No,No,No,Yes,Month-to-month,Yes,Electronic check,88.95,NaN,Yes,I recently decided to cancel my fiber optic in...,1323
79,9360-AHGNL,Female,1,Yes,No,43,Yes,Yes,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,109.55,NaN,Yes,I have been a customer with this company for o...,6588
122,7253-UVNDW,Female,0,No,No,46,Yes,No,DSL,No,No,Yes,Yes,No,No,Two year,No,Credit card (automatic),54.35,NaN,Yes,I have been a customer with this company for 4...,5277

In [61]:
df_nulos["Tempo_Permanencia(MESES)"].describe()

count        277.0
mean     29.696751
std      24.777161
min            0.0
25%            5.0
50%           25.0
75%           54.0
max           72.0
Name: Tempo_Permanencia(MESES), dtype: Float64

In [59]:
df_silver["Tempo_Permanencia(MESES)"] = pd.to_numeric(
    df_silver["Tempo_Permanencia(MESES)"],
    errors="coerce"
).astype("Int8")

## Mudando a tipagem dos dados e padronizando os formatos

In [63]:
df_silver.dtypes

ID_Cliente                   object
Genero                       object
Cliente_Idoso                 int64
Parceiro                     object
Dependentes                  object
Tempo_Permanencia(MESES)       Int8
Servico_Telefonico           object
Multiplas_Linhas             object
Servico_Internet             object
Seguranca_Online             object
Backup_Online                object
Protecao_Dispositivo         object
Suporte_Tecnico              object
Streaming_TV                 object
Streaming_Filmes             object
Contrato                     object
Faturamento_Sem_Papel        object
Metodo_Pagamento             object
Cobranca_Mensal             float64
Cobranca_Total              float64
Cancelamento                 object
Feedback_Cliente             object
Renda_Mensal                  int64
dtype: object

In [64]:
df_silver = df_silver.astype({
    "ID_Cliente": "string",
    "Genero": "category",
    "Cliente_Idoso": "bool",
    "Parceiro": "category",
    "Dependentes": "category",
    "Tempo_Permanencia(MESES)": "Int8",
    "Servico_Telefonico": "category",
    "Multiplas_Linhas": "category",
    "Servico_Internet": "category",
    "Seguranca_Online": "category",
    "Backup_Online": "category",
    "Protecao_Dispositivo": "category",
    "Suporte_Tecnico": "category",
    "Streaming_TV": "category",
    "Streaming_Filmes": "category",
    "Contrato": "category",
    "Faturamento_Sem_Papel": "category",
    "Metodo_Pagamento": "category",
    "Cobranca_Mensal": "float32",
    "Cobranca_Total": "float32",
    "Cancelamento": "category",
    "Feedback_Cliente": "string",
    "Renda_Mensal": "int32"
})

In [66]:
df_silver.dtypes

ID_Cliente                  string[python]
Genero                            category
Cliente_Idoso                         bool
Parceiro                          category
Dependentes                       category
Tempo_Permanencia(MESES)              Int8
Servico_Telefonico                category
Multiplas_Linhas                  category
Servico_Internet                  category
Seguranca_Online                  category
Backup_Online                     category
Protecao_Dispositivo              category
Suporte_Tecnico                   category
Streaming_TV                      category
Streaming_Filmes                  category
Contrato                          category
Faturamento_Sem_Papel             category
Metodo_Pagamento                  category
Cobranca_Mensal                    float32
Cobranca_Total                     float32
Cancelamento                      category
Feedback_Cliente            string[python]
Renda_Mensal                         int32
dtype: object

In [67]:
df_silver.head()

,ID_Cliente,Genero,Cliente_Idoso,Parceiro,Dependentes,Tempo_Permanencia(MESES),Servico_Telefonico,Multiplas_Linhas,Servico_Internet,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Faturamento_Sem_Papel,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cancelamento,Feedback_Cliente,Renda_Mensal
0,4578-PHJYZ,Male,False,Yes,Yes,52,Yes,No,DSL,No,Yes,Yes,Yes,Yes,No,One year,Yes,Electronic check,68.750000,3482.850098,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,False,Yes,Yes,33,Yes,No,DSL,No,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,73.900002,2405.050049,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,True,No,No,22,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,20.049999,417.000000,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,True,Yes,Yes,28,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,35.900002,973.650024,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,False,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.300003,144.000000,No,I have been using the fiber optic internet ser...,1691